#+TITLE: 政企平台
#+HTML_HEAD_EXTRA: <style>blockquote {font-style:normal; font-size: 0.8em}</style>



* 关于商业模式的思考
** 成胜文

#+BEGIN_QUOTE
老师，我开过淘宝店和做过微商，我接触过几种商业模式，水很深。。。

电子商务公司的商业模式：首先，这是一个第三方软件平台，用户为企业对加盟商，卖家是首先注册一个店铺，或者加盟一个电子商务公司，我当时是加盟一家电子商务公司，然后他是有四个套餐的，

第一种1480是帮你注册一家店铺，给你提供应商家，第二种是1880在第一种的基础上帮你装修店铺，其实按照现在来说就是帮你店铺换一个框架，相当一键换肤，当然，这也是吸引买家的一个小细节，第三种是2880，在第二种套餐下的帮你推广，也就是在淘宝平台上或者浏览器上推送小广告，然后还有个机器人帮你回复用户，第四种是3200，叫做托管模式，你只需关注订单，然后发货就可以了，这种电子商务公司的就相当于我不去卖物品，我直接招商入驻我公司，我给你提供货源，而利润的来源就是加盟费和长期入驻这个平台带来的流量营销。

淘宝的商业模式：我通过加盟有了店铺之后就可以加入到淘宝的卖家行列了，这时平台需要交1000块保证金，如果一个月内店铺没有更新，那就会关闭店铺，保证金就会退回，而现在的淘宝不是像以前一样，随便放放东西就有人买，现在的第一看销量，第二看评论，第三看性价比。卖家的销量在哪里来？那就先需要流量，放长线钓大鱼，这时就需要前面的电子商务公司的商业模式第三种套餐的推送方式，当店铺的浏览量大了，那店铺的排名就相对高一点，还有就是通过关注店铺和收藏店铺也会提高排名，有了前期的铺垫就是慢慢吸引用户了，用什么来吸引呢？相信听过一种天天特价吧，往往选上一种一天的销量都可以赚会加盟的成本，然后加盟商还有把加盟费退回给你，还会有一个年终销量奖的，这都是电子商务的背后商业模式操盘，实际上很少会赚回的，因为对手多，很难上天天特价，但是电子商务公司的运营模式就是抓住了人的一个弱点，往往都是明知道水很深都会选择去加盟商家，话扯回到淘宝的商业模式，当你店铺有了流量和基本的销量之后就是店铺的级别了，一般最底层的店铺就是一颗心，三颗心以上才可以去竞争天天特价，每日优惠等这些活动，加入这些活动是通过排名前三百家的商品才能选上的，这时候就有了一个途径，刷销量，但是现在已经查的很严，那应该怎么办呢？很简单，通过线下去找别人办银行卡，卡越多越好，不能是同一个人的，某一种意义上讲就是暗箱操作，然后用不同的银行卡使劲刷销量，当然大部分在晚上，这个是有讲究的，晚上一般都是流量的高峰期，可以降低一定的风险，早上的人一般都是看下时间、新闻，中午10点多也是一个高峰期，工作累了逛下淘宝有什么新衣服，这些简说一些，我之前入坑之前都有过了解，毕竟我也刷过销量什么的，然后就是当你店铺上了皇冠之后，店铺就有点成就了，这时候店家又可以通过些暗箱操作把衣服的价格都提升一点，衣服的价格上架都是可以调整的，然后有了天时地利人和，就等败家娘们剁手了，当然我也算一个，从此，卖家走向人生巅峰。。。。

--------------------

老师，我这一天一直在想一件事，什么是互联网？什么是政策？什么是时代的代表？

最后我想明白了，中国现阶段的互联网是处于风口浪尖上，都是想着政策的发展趋势在哪里？而我，想明白了，是大家都知道却不去注意的地方，就是共产主义，所有的政策的终点只有一个目标就是从社会主义过渡到共产主义，如果我没有猜错的话，现中国互联网还是处于管理从服务的转变的过程，虽然我真正接触互联网才短短两年不到，但是我已经感觉到很多东西都在潜移默化的改变我的思想，如果想要真正的迭代现阶段互联网的时代的想法，必须要往共产主义这方面去想，未来的共产主义的概念就是每个人都有一样的物质，什么都不缺的时代，那中国的唯物主义思想就达到顶峰了，比的就是唯心主义，说白了就是才华，精神上的是唯一取代不了的。

我打一个比喻，中国三家大型的互联网公司，阿里、百度、腾讯是一艘驰骋在互联网时代的航母，有无数企业家都寄托在航母去开店摆摊赚钱，那这三家公司会笑的开花，知道为什么吗？因为永远不可能有一丁点超越这艘航母的可能性，只能一直做一个寄生虫。航母是有寿命的，少数企业会想到在航母上找到这艘航母的不足处，然后去突破，比如某多多，但是大多数因为在航母上呆的久了，思想被框住了，新轮船总是没有敌不过航母的，我们只有找到这艘航母的终点在哪里，找到政策的终点在哪里，这样大方向确认下来，慢慢去规划路线，就完全可以打破三家独大的局面了，有一句话我喜欢，人生短暂几十年，如果能在人类历史上钉上一个自己名片，那就是一个时代的代表性人物，我觉得，我们做开发的，一定要敢想，哪怕这只是被别人当作笑话的想法、吹牛的想法、疯子的想法，从某一方面来说我也成功的营销了自己，起码能让别人想起这个笑话的想法是xxx的。

国美集团黄裕光，如果我没有猜错，我们班应该很少人知道这个名字吧，2006年的中国首富，因为偷税被抓了，但是现国美的市值也不会低于200亿，表面上是因为黄裕光的妻子在帮它打理才导致市值没有跌，那是因为黄裕光在监狱里用一个电话在为它妻子出谋划策，某一方面上这是一个枭雄...懒得打字了。。。。。。。
                                                                                                                                       
                                                                                                                                       2019、1、5    成胜文
#+END_QUOTE

** 李杰焜

#+BEGIN_QUOTE
商业模式

1、首先我们来看看官方的说法，商业模式：是管理学的重要研究对象之一， MBA、 EMBA等主流商业管理课程均对“商业模式”给予了不同程度的关注。在分析商业模式过程中，主要关注一类企业在市场中与用户、 供应商、其他合作伙伴的关系，尤其是彼此间的物流、信息流和资金流。 商业模式: 企业与企业之间、企业的部门之间、乃至与顾客之间、与渠道之间都存在各种各样的交易关系和连结方式称之为商业模式。。

对于我来说，一种商业模式主要是使企业与顾客之间的关系形成一个桥梁，同时要当下的市场主旋律相吻合。

例如我举一个例子：《秦时明月》，是玄机科技下的一部动漫作品，诞生于2007年，是国内创作的首部动漫，当时在国内充斥着各种国外漫画作品，是外漫的集中爆发期，而国漫没有人敢做，玄机是第一个，当时的玄机的《秦时明月》商业模式单一，靠的收视率，但当时的《秦时》画质粗糙、剧情逻辑不连贯，与当时的外漫相比，收益甚微，完全不是外漫的竞争对手，甚至有首部国漫要难产的流言蜚语。

但还好玄机找到了一种模式，技术情怀加扩展周边，一：首先把动漫的画质从二维提升到了三维使观众的观赏体验提升；二：内容与历史相结合，使其代入感更加强烈；三：目前玄机通过秦时明月其本上算在国内产业链部署上做的最完整了。从电影、电视剧、动漫、漫画、小说、游戏，各种衍生周边、舞台剧，所有的能够想到的产品形式，基本都已经涵盖。保证其动漫的质量同时加上看客与动漫的情怀，使其有了各种盈利方式。
#+END_QUOTE

** 陈子寒

#+BEGIN_QUOTE
给企业用户采用等级的限制，不同的等级对用着不同的权限，比如(0-5)级 能够免费发多少次申述，能够收到多少条推送，然后随着等级的提升，相对应享受的功能也有所提升。
也可以在企业用户申述的时候把企业申述的信息拦截，排列好，根据企业用户的等级再向政府进行信息推送。
也可以采用积分制度，比如实现某些操作给用户加积分，然后申述需要消耗积分。
当然需要用户粘度的话，前期不做任何的权限控制，等用户量提升了再做用户权限控制
#+END_QUOTE

** 刘志翔

#+BEGIN_QUOTE
主要想法有两种：

一、政府用户直接对企业用户。政府部门为主导，投资建立项目。项目搭建完毕后，把相关的管理和运营交给政府部门，由政府工作人员去做统一的规化和管理。这样做的话，项目具有一定的可复制性，一次开发多次使用，可以适用于各个地区的政府部门。但是具有一定的弊端，当使用该项目的地区过多时，不利于政府与政府之间的统一规划，无法把各个地区的政策相起来。关于网站的运营和管理，政府部门可能需要额外的投资，去聘请或培训相关人员，成本又一步提高。

二、提供一个平台，寻求、吸引相关政府部门入驻。因为企业用户是跟着政府的政策走的，当政府入驻成功后，可以吸引该地区相关企业入驻，关注相关的政府，订阅关心的政策。平台盈利模式可以稍作更改，政府免费入驻，只需按时交纳一定的平台运营和管理经费即可。这样做的话可以把政府部门从平台的运营和管理中释放出来，政府只需专注于政策的管理，节约时间成本。当入驻的政府和企业很多时，就可以提现出平台良好的拓展性，而且对于政府和企业的联合管理变的更加简单
#+END_QUOTE

** 梁均淋

#+BEGIN_QUOTE
通过看《政策信息发布平台》进行的一个总结：

1，  我们周五进行的一个对这个平台的营销方式的一个分享：

我认为，

不该进行对一个会员等级的一个划分（这个会员的功能可以留着，但不是前期启动），因为我们的一个现状是我们还没有将知名度提高，如果贸然通过会员收益，一定有人不买账（这个是看数量而已，我也并没有做市场调研），又或者说如果我们的产品可以达到碾压市场同类产品，我们也可以将这个业务加入其中。

不该进行对广告的织入，这个是一定不可以的（除了政府的一些正能量广告），我们是做的是政府与企业间的项目，如果我们的页面中嵌入大量的广告，这个对两者都有一个不好的影响，我建议杜绝这个想法，因为我们不必要赚第三方广告商的钱，而把我们的主要的两位“客人”给得罪了，得不偿失啊

我对这个平台的一个营销方案是（一个是裹在自己手里，一个是卖出去经营，我们可以赚一个版本费，功能费，还有一个是将两个整合起来，我们把一个后台版本卖给政府，然后他们进行一个政策发布，然后一个门户网站就我们经营）：

我们把产品做好，然后可以采取打赏的方式来进行运维（我推测大多数人是并没有进行打赏的），但是我们可以通过一个我们打赏来的钱，70%作为一个慈善资金（助学金的方式，我们可以将这个助学金的一个名单公示，并对一个助学金同学的一个展示，这样吸引企业招聘），通过这个小方案我们获取可以提高一个打赏度，到后期我们再决定是否启动会员功能，

2，  对于我们这个平台，我认为我们主要的几个方面一定要做好：

1，  对数据展示（政策的展示，以及一些政策相关的数据）

2，  政策分享（我们可以通过企业间，或企业内的一个数据分享，我们就可以大大提高知名度）

3，  网络数据采集（这个我们要提供相关人员负责又或者提高采集的算法，因为我们数据采集中难免有一些差错）

4，  对于政策评议的一个审核，避免使自身陷入舆论中

5，  暂时这么多，其实还有很多

1，  对于《政策信息发布平台需求规格说明书》：

1，  这个平台在我的眼里就是一个政府与企业间政策的一个交流平台，我们负责更好的去展示政策数据给企业，为企业推选出适合它的一个政策，企业将政策的一个回馈信息，我们就传递给政府（可能是我想的太少）

2，  我认为在上周中我们的同学提出的一个政策发布问题，我们只是一个中转站而已，我们并不会去多参与这个方面的问题，避免对自身不利

4，关于这个项目目前的一个想法：（当前是把我们要做什么搞清楚，因为我们班里还有很多人并不知道自己在干嘛）

1，  建立一个专门设计数据库的小组，专门去学习相关的知识，关于我们对数据库的一个知识（唉，不用多说，太弱了,弱得可怜）

2，  建立一个对系统架构的小组，学习专业的知识

3，  建立一个前端小组，学习专业知识

4，  将组调整好，然后进行分配任务，然后每周周五下午进行一个交流，交流组与组的一个进展，和一些技术点

5，  最后各司其职，由一个项目领导人去指挥项目，毕竟我们都是年轻人，谁也不服谁，到最后变的乱七八糟，所有我们是非常有必要有一个人站出来“话事”

5，最后我还是希望每个人在这个项目中找到“自己”
#+END_QUOTE

** 朱茂琛

#+BEGIN_QUOTE
商业模式无非就是想怎么样赚钱，怎么样运营下去。而作为写平台的我们应该思考的是我们从谁的手里赚这份钱，如何让客户对我们平台依赖性。

首先，这是一份可复制性的平台，也就是可以交给各地的政府为各地企业服务的。所以在项目的一期，也就是门户网站上只有关于“政策”这点内容的时候。这份钱的大头当然是从政府部门收取，因为他们需要各地的企业带动本地区的经济，所以需要让企业实时的当地出台什么样的政策，给予企业方面。小头就要从企业方去收取，例如我们可以利用“精准推送”，“语音播报”等功能进行收取佣金。为什么可以从这方面吸取佣金呢？因为企业希望即时的看到对于自己企业相关的利好消息。

其次，不排除我们平台的后期扩展，我们可以从投融资方面入手。既然投融资就要涉及到金主，而手里最有闲钱的，又不怕企业还不上或者赚不到钱，必属--银行，所以可以和银行合作。这方面可以如何赚银行的钱还没有想好，但是必定要从银行的手中赚取一份佣金。

最后，总结一下平台的优势。第一，平台是政策的集合地，政府部门可以省去一部分宣传的精力，也可以即时收取到企业的需求，不在消息闭塞。第二，企业可以从平台上实时看到有关自己企业相关方面的消息，即时对企业做出相关的调整。第三，在前两条优势建立后，平台上企业就多了。所以银行的入驻的条件就建立了，因为企业总是有缺钱的地方，而在平台上可以方便进行融资。
#+END_QUOTE

** 李玉聪

#+BEGIN_QUOTE
首先就项目而言，文档就已经指明了是主要面向企业(游客亦可浏览)，故而我主张的是从【功能拓展】方面进行收费理由如下：
①我们这个项目本身并没有火起来，而且公司知名度也不够，这也就注定了我们无法通过项目收费使用来获取利益
②本项目是用于政策浏览使用的，所以尽量不使用广告，保证其严肃性
③功能扩展收费在国外也有先例。具有可行性
具体：
虽然本项目是用于政策浏览，但其根本目的在于解决企业问题，我们可以在保证政策浏览的前提下，扩展一些企业发布需求的功能，如急需某些资源(如猪饲料),【我们称之为发布需求】，其他具有这些资源的企业在浏览到其需求是则可以进行快速支援，我们称之为【回复需求】，我们则在发布需求和回复需求上进行一定的收费，但这只是目前我本人想到的一个功能，我相信远远不止这一个
#+END_QUOTE

** 罗毅

#+BEGIN_QUOTE
政务平台商业盈利模式

没有盈利一切都是空谈，盈利模式决定着一个平台的现状以及未来。所以做好商业盈利模式的策划非常重要

1．政务平台的基本业务，也就是政策的发布，以及精准投放到企业用户的手里这个过程是不能改动的

1)采集 -> 审核 -> 发布

2)编辑 -> 发布

3)企业用户 -> 订阅 -> 政策投放

2．平台的盈利，都需要在用户的基数多的情况下才能进行。那我们平台开发完成后可以申报政府的投资。把平台的权限给到当地政府，而这个平台的模式也是可以复制的，不仅珠海本地，以及其他地方都可以使用这个模式。也就是一次性半买断的行为，为什么叫做半买断？我们需要平台运行时候企业用户访问的记录做一个大数据，这些大数据也是决定着我们以后的盈利做铺垫

3．当我们的企业用户有一定的数量之后，可以根据大数据的情况分析出那些企业，那种企业，需要一些什么服务，而这些数据分析出来的数据，我们可以通过这些数据来针对不同的企业去提供给不同的第三方做其他的服务，例如数据上反映出某些企业有某些需求，那我们作为运营者就可以给第三方提供供求，第三方从我们这里得到脱敏后的数据，作为交换支付酬劳、大数据不仅可以做这一点，因为大数据简化了决策流程，不要看“为什么”，只需要看“是什么” ，从因果关系变成了相关关系。比如蛋挞的销量与飓风天气有关，啤酒放在尿不湿旁边会卖得更好。在这里，我们不一定非得知道为什么飓风一来蛋挞销量就会上升，只需要知道两者之间存在这种关联即可。大数据对平台以后发展的道路有很大的帮助。

4．我们不仅可以做大数据盈利模式，还可以做增值服务，鸡蛋不要放在同一个篮子里面。但是最主要的还是不能改变最基本的服务，也就是第一点提到的。
#+END_QUOTE

** 方成龙

#+BEGIN_QUOTE
我认为这个商业的模式主要是这样的：企业<-- 平台 -->政府，我们提供平台给企业，不过也要分特权的。就像QQ开会员那样，企业如果开"普通会员"，我们可以每个月推送相应的政策信息给他们。如果开"超级会员"，我们可以一对一对他提出的问题，进行分析，从而寻找相应的政策。政府使用我们这个平台的话，开"会员"的方式肯定是不行的。毕竟政策是政府颁发出来的，政府想要的是收集各个企业的问题。所以对政府可以进行季度收费或者月收费。把企业的问题都分起类来，方便政府笼统的颁布相应的政策！
#+END_QUOTE

** 欧健平

#+BEGIN_QUOTE
1、平台出来后，每谈拢一个地方政府，我们就可以直接给定一个账号政府，用于发布相关政策，只给一个账号是为了避免账号泛滥
2、谈拢政府后，为了能让平台能运行起来，并有访问量，我们就需要去和企业谈了。
3、每一间企业免费体验一个月，后续每月需要缴费，平台会推出月卡，季度卡，年卡这3种缴费方式。如果没有缴费，你只能阅读平台推荐的，订阅功能会自动关闭。
4、也有会员缴费方式，如果升级为会员缴费方式，那么，我们就不需要向平台缴纳平常的费用。
5、一星会员：平台会对用户开放订阅功能
   二星会员：平台会对用户开放精准推送功能、提诉求面板（延迟发送到政府工作人员的信息箱中）以及一星会员所拥有的权利
   三星会员：平台会对用户开放企业交流版块、以及诉求及时发出权利（企业可以通过这个版块进行交谈，相当于一个讨论群）以及二星会员所拥有的权利。
6、每个企业账号一个月只能拥有一次发诉求的限制，如果需要提交第二次诉求，非三星会员需缴费，三星会员只拥有两次机会，如再需要，需缴费。
#+END_QUOTE

** 陈绍基

#+BEGIN_QUOTE
政企营

(作为政府政策和企业交互的一个平台)


   作为一项政策与企业交互的平台，我们秉着向政府大众服务的心态把平台做大做强，以从千万相同平台官网中脱颖而出。本平台在与以往政策官网不同之处，我们不仅继承了原本政府官网对政策的收集和分类等，还额外扩展了对政策的精准推送以及相关企业之间的信息推送等。我们先从珠海市开始，然后到省、国进发。

   对于政策，在前期来说我们无法强迫政府等相关部门入驻我们的平台，所以我们主要的信息来源是从政府相关的官网进行收集，一方面我们可以解决政策真实性的问题，另一方面我们还可以进一步的加入标签、类型、范围等分类（为了后期不仅能精准推送，还能做到相关企业之前的信息互动）。中后期可再加入新闻、演讲、市文化，可以多种情势的推广国情、市情。

   对于大众，所有人在我们的平台都可以以游客的方式进行体验，可以很直接的感受到我们主页的信息量和分类明细。对于游客，可以在公告栏中收到主席演讲、市级大事。对于企业，不同的企业规模、企业方向收到相关值得阅读政策。对于营销，我们可以通过它销售的东西还可以接收到一些相关的信息和物品，比如：养殖的还可以接收到屠宰的信息（可以理解出一种一条龙的服务）。还有很多就不一一介绍了，除了游客之外，其它的企业什么的都需要进行用户和个人信息企业信息的注册，这样我们我们就可以根据用户的每一步操作，和注册的信息做到精准的推送。

   对于政府，在中期我们的政策以及用户流量等信息不断膨大后，我们可以向当地政府推售我们的平台，在政府方部署我们的平台，在有新政策推出或新闻那些时，政府可以直接在我们平台进行发布，这样就可以从之前政府对企业当方面的对接升为双方的交互，政府不仅可以了解到企业、营销、游客的信息、反馈、关注点，企业也可以时时的关注到政策、国家动向。当然，在维护和运营方面还是由我们来负责，向政府商谈相应的开发费用和维护未用。

   对于未来发展，我们可以接入一些语音合成，和所谓的专家分析，还有企业招聘、公务员讲座等等功能以及业务，形成我们如上所说的一条龙服务。这样可以让游客更好的了解到本市的信息，也可以然刚入住的外地人了解到本市的情形。
#+END_QUOTE

** 农梓鸿

#+BEGIN_QUOTE
一、什么是商业模式

商业模式是由创业者，提出的一套能实现赚钱的模式，只要能稳赚钱，就是好的商业模式。
有一个好的商业模式，成功就有了一半的保证，具体就是通过什么途径或方式来赚钱。
首先：是一个满足消费者的需求的系统，这个系统能为消费者提供有效的服务，因此还要具备有自己能复制且别人不能复制，或者自己在复制中占据市场优势的地位。


二、商业模式六要素：
1、定位
2、业务系统
3、关键资源能力
4、盈利模式
5、自由现金流结构
6、企业价值


三、免费模式
免费模式是最伟大的商业模式，很多人看不懂背后的商机，免费模式可以给大家带来好处有
1、带来人气
2、有助于品牌的传播
3、让过客成为顾客
就像谷歌一样，使用都是免费，为什么能赚那么多钱，就是这个道理。
#+END_QUOTE

** 罗政委

#+BEGIN_QUOTE
关于上个星期班里讨论的商业模式，有关政企云这个项目来说，该项目的商业模式，上周也有同学分享的很不错，继上次的分享收获和自我的理解总结一下该项目的商业模式。
商业模式在我的理解之中就是商业的一种形式。对于进行项目商业化的管理。在做项目之前要明确项目的目的是为了做什么。有什么功能，可以为什么人员服务，以及如何才能让这个项目有价值的体现，
在项目启动之初就要考虑这些问题，关于怎样让这个项目体现出价值，项目就要有一定的商业模式。
政企云这个项目来说：主要是政策的采集和信息的发布以及用户的订阅等等，政策的采集都是比较权威的，因为这些政策信息必须要保证准确性。信息的发布也需要保证间隔性，在不同的时间段发布不同的信息。
我觉得用户的订阅就有一定的商业模式了，一个用户的订阅意味着有人在使用这个项目，这个项目就有价值，如果能保证每条政策的发布对每个用户都有参考价值，那么就能吸引跟多人来使用这个项目。这就是我认为这个项目的初级商业模式，当然还有很多模式需要我们去探索。
#+END_QUOTE

